### ISSUE TITLE
拋磚引玉：想問這個可以加入嗎？

### ISSUE THREAD

**Issue by cytsunny** [hkgos/awesome-hk-open-source#1]
不知道你們要多大的 project 才可以加入，但抱著拋磚引玉的心態，就試試把我自己的蚊型 repository 放上來，就算失敗都可以作為示範給後面知道大概你們要些甚麼樣的 project:

Repository名稱：中文亂文隨機生成器
URL：https://github.com/cytsunny/randChinese
語言： PHP
用途分類：語言相關？
簡介：隨機生成測試用的中文正體字。

**Comment by edmondyip** [comment]
Project無分大小，非常多謝你有心加入你的project
我地會再作分類處理
多謝支持
