### ISSUE TITLE
支持：LIHKG Vue 版

### ISSUE THREAD

**Issue by colloquet** [hkgos/awesome-hk-open-source#2]
Repository名稱：LIHKG Vue.js 版
URL：https://github.com/colloquet/lihkg-web
語言： JavaScript
用途分類：社交媒體
簡介：用 Vue.js 寫既 LIHKG client

**Comment by edmondyip** [comment]
我之前就有睇過你個project(因為我都係玩Vue)
高質

**Comment by colloquet** [comment]
多謝🙇

希望有機會合作做下 D project 仔🤝

**Comment by benchan1997** [comment]
師兄入左tg group未

**Comment by colloquet** [comment]
未，條 invite link telegram x 食唔到😂
返屋企先 join
