### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by Jasonlhy** [hkgos/awesome-hk-open-source#3]
支持下

Repository名稱：VSCode-Hungry-Delete
URL：https://github.com/Jasonlhy/VSCode-Hungry-Delete
語言： TypeScript
用途分類：VSCode Extension
簡介：VSCode Extension, 用嚟 Hungry Delete

Repository名稱：VSCode-Browser-Sync
URL：https://github.com/Jasonlhy/VSCode-Browser-Sync
語言： TypeScript
用途分類：VSCode Extension
簡介：VSCode Extension, 用嚟 integrate browser sync

**Comment by Jasonlhy** [comment]
重有兩個之前高登巴打整既，不過好似無人再 main sosad

Repository名稱：PHP-Endless-Battle
URL：https://github.com/c0re100/PHP-Endless-Battle
語言： PHP
用途分類：Game
簡介：Web Gae 無盡的戰鬥 

Repository名稱：golden-cache
URL：https://github.com/mingchuno/golden-cache
語言： Scala, Angular
用途分類：Website
簡介：以前高登好慢 cache 低用嚟上高登快啲

**Comment by edmondyip** [comment]
多謝巴打支持！

**Comment by cytsunny** [comment]
孤陋寡聞，可否介紹一下「無盡的戰鬥」是什麼？我 Google 過，無論「無盡的戰鬥」還是「Endless-Battle」的名字都似乎沒有很詳細的介紹。

最關鍵是 Repository 裡面沒有 License。因為似乎遊戲不出名，推斷遊戲公司規模小，即使是私服，也可能無力採取法律行動。但這樣根本不是 Open Source，不應在這個頁面出現？

**Comment by benchan1997** [comment]
原作者為: http://forum.v2alliance.net/index.php ，版權應為 v2alliance 所有。因此我們會將其除名。

> php-eb v0.50 RC1
> 這是 Release Candidate,
> 由於時間關係, 只提供有限度技術支援~
> 
> 引用一下舊文內容:
> 引用:
> 若您想自架 php-eb, 而又確定自己對 php 有一定程度的認識,
> 我們樂意向閣下發送程式原檔!!
> 
> 但為了避免嚴重灌水、以及 php-eb 的胡亂發佈,
> 二零零七年三月十日起,
> 正式改以 E-Mail 方式公開!
> 另外:
> **1. v2Alliance 極度重視版權資訊, 請勿更改！**
> 2. RC 版只是 RC 版, 日後公開的版本或許會有重大更新...
> 3. Database 還會有一定程度的更新, RC1 沒有這是資訊
> 4. RC1 是非常貼近 v0.50 Open Test 的版本, 可以去測試伺服器看看
> 
> 安裝須知:
> 1. 開 config.php, 改改設定, 有簡單設定的
> 2. 開 others/phpeb.sql, 把資料表前綴改好, 用 phpMyAdmin 匯入
> 3. 把 others 以外, 所有其他的資料夾及檔案上載
> 4. others 資料夾含有 testscripts 及 tools, 請自行研究有什麼用途 XD, 並根據需要上載/執行
> 
> 環境需求:
> PHP 5.x
> MySQL 5.x
