### ISSUE TITLE
鋤DEE A/B 網上對戰 Client

### ISSUE THREAD

**Issue by colloquet** [hkgos/awesome-hk-open-source#6]
Repository名稱：鋤DEE A/B 網上對戰 Client
URL：https://github.com/colloquet/big2-client
語言： JavaScript
用途分類：遊戲
簡介：用 React.js 寫既小遊戲

**Comment by benchan1997** [comment]
個中指好正

**Comment by colloquet** [comment]
係我朋友既 idea 😂
